# Change these first
owner: netbootxyz # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: netboot.xyz
    url: https://netboot.xyz
  - name: boot.netboot.xyz
    url: https://boot.netboot.xyz

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.netboot.xyz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: netboot.xyz
  introTitle: "**netboot.xyz** infrastructure status"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
